Initializing Tensors

In [7]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device='cpu', requires_grad=True)

In [8]:
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [9]:
device

'cpu'

In [10]:
print(my_tensor.device)
print(my_tensor.dtype)
print(my_tensor.shape)
print(my_tensor.requires_grad)

cpu
torch.float32
torch.Size([2, 3])
True


In [11]:
torch.eye(5,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
torch.arange(start=0,end=5,step=.5)

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000])

In [16]:
torch.linspace(start=0.1, end=1, steps=10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

Convert the Numbers

In [18]:
torch.arange(4).bool()

tensor([False,  True,  True,  True])

In [19]:
torch.zeros(12,14)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Mathematical Operations

In [23]:
torch.add(torch.tensor([1,2,3]), torch.tensor([1,2,3]))

tensor([2, 4, 6])

In [24]:
a = torch.tensor([1,2,3])
b = torch.tensor([5,6,7])

In [29]:
torch.add(b,a)

tensor([ 6,  8, 10])

In-place operations

In [30]:
b.add_(a)

tensor([ 6,  8, 10])

In [31]:
b

tensor([ 6,  8, 10])

In [32]:
x = torch.rand((5,3))

In [33]:
y = torch.rand((3,5))

In [34]:
torch.mm(x,y)

tensor([[0.1201, 0.4165, 0.1718, 0.1419, 0.3966],
        [0.3835, 1.1033, 0.3571, 0.2408, 1.0794],
        [0.2264, 0.6875, 0.1239, 0.1749, 0.6510],
        [0.2917, 1.3115, 0.4566, 0.6232, 1.1816],
        [0.4956, 1.5659, 0.6619, 0.4430, 1.5219]])

In [37]:
x[:,0]

tensor([0.2067, 0.8979, 0.5207, 0.2406, 0.9941])

In [38]:
y[0,:]

tensor([0.3617, 0.9185, 0.1301, 0.1117, 0.9031])

In [36]:
torch.dot(x[:,0],y[0,:])

tensor(1.8919)

Boadcasting

In [39]:
x1 = torch.rand([5,5])
y1 = torch.rand([5,1])

In [40]:
x1 - y1

tensor([[-0.6982, -0.7207,  0.1239, -0.0361, -0.5258],
        [-0.2337, -0.7321, -0.8327, -0.9446, -0.4756],
        [-0.5853,  0.3507,  0.0597,  0.3112,  0.3418],
        [ 0.2020,  0.3568,  0.8657, -0.0471,  0.2521],
        [-0.3935,  0.1655, -0.6681, -0.2663, -0.4777]])

In [41]:
torch.t(x1) + torch.t(y1)

tensor([[0.8941, 1.7275, 0.7032, 0.4017, 1.1591],
        [0.8716, 1.2290, 1.6392, 0.5565, 1.7181],
        [1.7162, 1.1284, 1.3483, 1.0653, 0.8846],
        [1.5562, 1.0165, 1.5998, 0.1526, 1.2863],
        [1.0665, 1.4855, 1.6304, 0.4518, 1.0749]])

In [43]:
x1

tensor([[0.0980, 0.0755, 0.9201, 0.7601, 0.2703],
        [0.7469, 0.2484, 0.1478, 0.0359, 0.5050],
        [0.0590, 0.9949, 0.7040, 0.9555, 0.9861],
        [0.3019, 0.4566, 0.9655, 0.0528, 0.3520],
        [0.3828, 0.9418, 0.1082, 0.5100, 0.2986]])

In [47]:
torch.sum(torch.tensor([0.0980, 0.7469, 0.0590, 0.3019, 0.3828]))

tensor(1.5886)

In [42]:
torch.sum(x1, dim=0)

tensor([1.5885, 2.7173, 2.8456, 2.3143, 2.4119])

In [50]:
torch.sort(x1,dim=0,descending=False)

torch.return_types.sort(
values=tensor([[0.0590, 0.0755, 0.1082, 0.0359, 0.2703],
        [0.0980, 0.2484, 0.1478, 0.0528, 0.2986],
        [0.3019, 0.4566, 0.7040, 0.5100, 0.3520],
        [0.3828, 0.9418, 0.9201, 0.7601, 0.5050],
        [0.7469, 0.9949, 0.9655, 0.9555, 0.9861]]),
indices=tensor([[2, 0, 4, 1, 0],
        [0, 1, 1, 3, 4],
        [3, 3, 2, 4, 3],
        [4, 4, 0, 0, 1],
        [1, 2, 3, 2, 2]]))

In [54]:
xx = torch.randint(20,(10,10))

In [60]:
xx%2 == 0

tensor([[ True,  True,  True, False,  True, False,  True, False, False, False],
        [False,  True, False, False,  True,  True,  True, False, False,  True],
        [False, False,  True, False,  True, False, False, False,  True,  True],
        [ True,  True, False, False,  True, False,  True, False,  True,  True],
        [ True, False, False,  True, False,  True, False, False, False, False],
        [False, False,  True,  True, False,  True,  True,  True, False,  True],
        [ True, False, False,  True,  True,  True,  True,  True, False, False],
        [ True, False,  True,  True, False, False, False,  True, False, False],
        [ True, False,  True,  True,  True,  True,  True, False, False,  True],
        [ True, False,  True,  True, False,  True,  True, False,  True, False]])

In [64]:
(xx%2 == 0).nonzero() == (xx%2 == 0).nonzero().squeeze()

tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [T

In [62]:
(xx%2 == 0).nonzero().squeeze()

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [0, 4],
        [0, 6],
        [1, 1],
        [1, 4],
        [1, 5],
        [1, 6],
        [1, 9],
        [2, 2],
        [2, 4],
        [2, 8],
        [2, 9],
        [3, 0],
        [3, 1],
        [3, 4],
        [3, 6],
        [3, 8],
        [3, 9],
        [4, 0],
        [4, 3],
        [4, 5],
        [5, 2],
        [5, 3],
        [5, 5],
        [5, 6],
        [5, 7],
        [5, 9],
        [6, 0],
        [6, 3],
        [6, 4],
        [6, 5],
        [6, 6],
        [6, 7],
        [7, 0],
        [7, 2],
        [7, 3],
        [7, 7],
        [8, 0],
        [8, 2],
        [8, 3],
        [8, 4],
        [8, 5],
        [8, 6],
        [8, 9],
        [9, 0],
        [9, 2],
        [9, 3],
        [9, 5],
        [9, 6],
        [9, 8]])

In [56]:
xx[xx%2 == 0]

tensor([ 8, 12, 14,  0,  6, 16,  2, 14, 10,  2,  4,  6,  8,  4,  0, 16,  2,  6,
         8,  8, 14,  2, 14, 10, 18,  2,  8,  0, 12,  6,  8, 18, 18, 12, 18,  2,
        16, 16,  4,  8,  8,  6, 10, 12, 10, 18,  0, 10,  8,  2,  0,  2])